### PR TITLE
Typed GSS interpreter

### PR DESCRIPTION
**Pull request by Inviz**
This is a 2nd full rewrite of GSS. The last one. It's good enough as a foundation for all future stuff.

It generates pre-defined lookup signatures to implement multimethods. Has somewhat friendlier error messages in some cases. The code is a lot more structured now, and it's never been easier to customize things.

Other notable additions:
- Variable hoisting (unscoped variables and virtuals point to topmost instance)
- :visible, :visible-y, :visible-x pseudo classes that fire up when element is visible
- computed- pseudo property family which acts like intrinsic- without resetting original property
- ^, ^^, ^^^... and $ combinators that point to parent/root scopes 
- Conditions now have a passable support for plural selectors. Atleast it wont hang 
- Simplistic units support (not in parser yet), em, rem, vh, vw, vmax, vmin. 
- One-way binding through px unit. Allows for some non-linear expressions not possible otherwise
- max, min functions that also provide some indirection
- Buffered console that outputs input and output next to each other keeping tree structure
- $scroll-top, $computed-height now work in a similar way to ::window[scroll-top] and ::window[height]
- Better scoped stylesheets support (no emulation for css dumping yet),
- Hoisted variables in top root scope are not global anymore, they are attached to stylesheet
- Scoped stylesheets in <body>,<head> or <html> define global variables in top scope, otherwise they attach to scope element.
- @import support (css dumping support is not reliable yet there). importing sheet multiple times is only parsed once.

What's coming:
- Custom property families with more css features
- Matrix support and an abstraction for sequence of operations. Spring animations plugin.

### CODE REVIEW

**Comment by paulyoung** [comment]
This branch appears to add files back into the `components`directory which was removed.

The diff is too big for GitHub, checking it out locally.

**Comment by paulyoung** [comment]
It also restores `src/gss.coffee` which was removed earlier.

**Comment by paulyoung** [comment]
The tests currently don't even run. Fixing.

**Comment by paulyoung** [comment]
The build is now failing on Travis because of the `saucelabs-mocha` task: https://travis-ci.org/gss/engine/builds/47561285#L802

**Comment by paulyoung** [comment]
Fixing conflicts now.

**Comment by paulyoung** [comment]
Chrome is failing now too :cry:

**Comment by Inviz** [comment]
Yeah, though `passes: 158` is a bit confusing, should be more like 230. I'll figure it out.

**Comment by paulyoung** [comment]
I updated `ccss-compiler` and `error-reporter` and published to npm this morning so there should be no need to patch `gss.js`, unless you meant something else?

In any case, patching the compiled output isn't a good idea. Travis will overwrite it anyway before running tests.

**Pull request merged**
