### PR TITLE
Changes to Gruntfile

### PR DESCRIPTION
**Pull request by paulyoung**
* Move `specs.js` out of `dist` directory.
* Split `browserify` and `watch` tasks into `dist` and `spec`.

This should allow `grunt watch:spec` and `grunt watch:src` or just `grunt watch` for both.

Please review :raised_hands:

### CODE REVIEW

**Comment by paulyoung** [comment]
I stuck with "specs" but it might be nice to keep things consistent and use "spec" as is used elsewhere in the file already.

**Comment by Inviz** [comment]
I tried this browserify setup too, but it didnt really observe specs for me, when I put two watch definitions.

**Comment by Inviz** [comment]
Interesting travis error. Any ideas?

**Comment by paulyoung** [comment]
Yep, on it.

**Comment by paulyoung** [comment]
@Inviz over to you I think.

**Comment by paulyoung** [comment]
Bump :facepunch:

**Comment by paulyoung** [comment]
There are some failing specs here that appear to be unrelated.

**Pull request merged**
